import { z } from "zod";

import type { Enums } from "@/core/supabase/types";

export const IMBUING_SCROLL_ITEM_KEYS = [
  "gold_token",
  "vampire_teeth",
  "bloody_pincers",
  "piece_of_dead_brain",
  "rope_belt",
  "silencer_claws",
  "grimleech_wings",
  "sabretooth",
  "protective_charm",
  "vexclaw_talon",
  "gloom_wolf_fur",
  "flask_of_embalming_fluid",
  "mystical_hourglass",
  "piece_of_swampling_wood",
  "snake_skin",
  "brimstone_fangs",
  "green_dragon_leather",
  "blazing_bone",
  "draken_sulphur",
  "winter_wolf_fur",
  "thick_fur",
  "deepling_warts",
  "wyvern_talisman",
  "crawler_head_plating",
  "wyrm_scale",
  "cultish_robe",
  "cultish_mask",
  "hellspawn_tail",
  "elvish_talisman",
  "broken_shamanic_staff",
  "strand_of_medusa_hair",
  "elven_scouting_glass",
  "elven_hoof",
  "metal_spike",
  "tarantula_egg",
  "mantassin_tail",
  "gold_brocaded_cloth",
  "lions_mane",
  "moohtah_shell",
  "war_crystal",
  "cyclops_toe",
  "ogre_nose_ring",
  "warmasters_wristguards",
  "orc_tooth",
  "battle_stone",
  "moohtant_horn",
] as const;

export const IMBUING_SCROLL_KEYS = [
  "scroll_strike",
  "scroll_vampirism",
  "scroll_void",
  "scroll_bash",
  "scroll_chop",
  "scroll_epiphany_powerful",
  "scroll_epiphany_intricate",
  "scroll_punch",
  "scroll_slash",
  "scroll_precise",
  "scroll_cloud_fabric",
  "scroll_demon_presence",
  "scroll_dragon_hide",
  "scroll_quara_scale",
  "scroll_snake_skin",
  "scroll_lich_shroud",
] as const;

export const ImbuingPriceKeySchema = z.enum([
  ...IMBUING_SCROLL_ITEM_KEYS,
  ...IMBUING_SCROLL_KEYS,
]) satisfies z.ZodType<Enums<"imbuing_price_key">>;

export type ImbuingPriceKey = z.infer<typeof ImbuingPriceKeySchema>;
