export enum AppErrorCodes {
  FOREIGN_KEY_VIOLATION = "FOREIGN_KEY_VIOLATION",
  INVALID_PAYLOAD = "INVALID_PAYLOAD",
  INVALID_QUERY_PARAMS = "INVALID_QUERY_PARAMS",
  NOT_FOUND = "NOT_FOUND",
  PERMISSION_DENIED = "PERMISSION_DENIED",
  SERVER_ERROR = "SERVER_ERROR",
  UNAUTHORIZED = "UNAUTHORIZED",
  UNIQUE_VIOLATION = "UNIQUE_VIOLATION",
  VALIDATION_ERROR = "VALIDATION_ERROR",
}
