import type { z } from "zod";

import { CharacterCharmDetailedSchema, CharacterCharmSchema } from "./charm.character.schema";

export const CharacterCharmUpsertPayloadSchema = CharacterCharmSchema.omit({
  id: true, // id is generated by the server
});

export const FetchCharacterCharmsResponseSchema = CharacterCharmDetailedSchema.array();
export type FetchCharacterCharmsResponse = z.infer<typeof FetchCharacterCharmsResponseSchema>;
