import { LocalDatetime, NonEmptyString, NonNegativeInt, PositiveInt, z } from "@repo/validation";
import type { Tables } from "../../../types";
import { CharacterIDSchema } from "../../characters/schemas";
import { CharmSchema } from "../../charms";
import { DamageElementSchema } from "../../damage-elements";
import { HuntPlaceSchema } from "../../hunt-places/schemas";
import { ItemSchema } from "../../items/schemas";
import { MonsterSchema } from "../../monsters/schemas";
import { PreyBonusSchema } from "../../prey-bonuses/schemas";
import {
  HuntSessionDamageElementSchema,
  HuntSessionDamageSourceSchema,
  HuntSessionKilledMonsterSchema,
  HuntSessionLootedItemSchema,
  HuntSessionMonsterDamageSourceSchema,
  HuntSessionSupplySchema,
} from "./hunt-session-relations.schema";

// --- 1. BASE DB SCHEMAS ---

/** Fields that are stored in the DB and can be set on insert/update */
export const HuntSessionDbBaseFieldsSchema = z.object({
  id: PositiveInt,
  character_id: CharacterIDSchema,
  place_id: HuntPlaceSchema.shape.id,
  date: NonEmptyString,
  started_at: LocalDatetime,
  ended_at: LocalDatetime,
  level: PositiveInt,
  player_count: PositiveInt,
  duration_seconds: PositiveInt,
  profit: z.number(),
  loot_value: PositiveInt,
  supplies_cost: PositiveInt,
  damage: PositiveInt,
  healing: PositiveInt,
  raw_xp_gain: PositiveInt,
  xp_gain: PositiveInt,
});

/** Computed fields generated by the database (Read-only) */
const HuntSessionDbFieldsComputedSchema = z.object({
  created_at: z.string(),
  updated_at: z.string().nullable(),
  raw_xp_per_hour: PositiveInt,
  profit_per_hour: z.number(),
  healing_per_hour: PositiveInt,
  damage_per_hour: PositiveInt,
  xp_per_hour: PositiveInt,
});

/** Full DB record schema (mapping 1:1 with 'hunt_sessions' table) */
export const HuntSessionDbFieldsSchema = HuntSessionDbBaseFieldsSchema.merge(
  HuntSessionDbFieldsComputedSchema
) satisfies z.ZodType<Tables<"hunt_sessions">>;

export type HuntSessionDbFields = z.infer<typeof HuntSessionDbFieldsSchema>;

// --- 2. DOMAIN MODELS (WITH RELATIONS) ---

/** Full session model with all relations (for Single View) */
export const HuntSessionSchema = HuntSessionDbFieldsSchema.extend({
  place: HuntPlaceSchema,
  killed_monsters: HuntSessionKilledMonsterSchema.array(),
  supplies: HuntSessionSupplySchema.array(),
  looted_items: HuntSessionLootedItemSchema.array(),
  damage_elements: HuntSessionDamageElementSchema.array(),
  monster_damage_sources: HuntSessionDamageSourceSchema.array(),
});

export type HuntSession = z.infer<typeof HuntSessionSchema>;

/** Simplified session model (for List View) */
export const HuntSessionListItemSchema = HuntSessionDbFieldsSchema.pick({
  id: true,
  date: true,
  duration_seconds: true,
  level: true,
  created_at: true,
  raw_xp_per_hour: true,
  profit_per_hour: true,
}).extend({
  place: HuntPlaceSchema.pick({ id: true, name: true, image_path: true }),
});

export type HuntSessionListItem = z.infer<typeof HuntSessionListItemSchema>;

// --- 3. INPUT/PAYLOAD SCHEMAS ---

const HuntSessionKilledMonsterInputSchema = z.object({
  monster_id: MonsterSchema.shape.id,
  count: PositiveInt,
  prey_bonus_id: PreyBonusSchema.shape.id.nullable().optional(),
  charm_bonus_id: CharmSchema.shape.id.nullable().optional(),
});

const HuntSessionItemInputSchema = z.object({
  item_id: ItemSchema.shape.id,
  count: PositiveInt,
});

const HuntSessionDamageElementInputSchema = z.object({
  damage_element_id: DamageElementSchema.shape.id,
  percent: z.number().positive(),
});

const HuntSessionMonsterDamageSourceInputSchema = z.object({
  monster_id: HuntSessionMonsterDamageSourceSchema.shape.id,
  percent: z.number().positive(),
});

/** Payload for creating a new session (excludes DB-generated ID) */
export const CreateHuntSessionPayloadSchema = HuntSessionDbBaseFieldsSchema.omit({
  id: true,
}).extend({
  killed_monsters: HuntSessionKilledMonsterInputSchema.array(),
  looted_items: HuntSessionItemInputSchema.array(),
  supplies: HuntSessionItemInputSchema.array(),
  damage_elements: HuntSessionDamageElementInputSchema.array(),
  monster_damage_sources: HuntSessionMonsterDamageSourceInputSchema.array(),
});

export type CreateHuntSessionPayload = z.infer<typeof CreateHuntSessionPayloadSchema>;

export const UpdateHuntSessionPayloadSchema = CreateHuntSessionPayloadSchema.extend({
  id: HuntSessionDbBaseFieldsSchema.shape.id,
});

export type UpdateHuntSessionPayload = z.infer<typeof UpdateHuntSessionPayloadSchema>;

export const DeleteHuntSessionPayloadSchema = z.object({
  id: HuntSessionDbBaseFieldsSchema.shape.id,
  character_id: CharacterIDSchema, // Fixed: changed to snake_case
});

export type DeleteHuntSessionPayload = z.infer<typeof DeleteHuntSessionPayloadSchema>;

// --- 4. QUERY & FILTER SCHEMAS ---

const PaginationSchema = z.object({
  page: z.number().int().min(1).default(1),
  limit: z.number().int().min(1).max(100).default(20),
});

export const HuntSessionFiltersSchema = PaginationSchema.extend({
  sortBy: z.string().optional(),
  sortDirection: z.enum(["asc", "desc"]).optional(),
});

export type HuntSessionFilters = z.infer<typeof HuntSessionFiltersSchema>;

/** Payload for fetching a single session */
export const FetchHuntSessionPayloadSchema = HuntSessionDbBaseFieldsSchema.pick({
  id: true,
  character_id: true,
});

export type FetchHuntSessionPayload = z.infer<typeof FetchHuntSessionPayloadSchema>;

export const FetchHuntSessionListPayloadSchema = HuntSessionFiltersSchema.extend({
  character_id: CharacterIDSchema,
});

export type FetchHuntSessionListPayload = z.infer<typeof FetchHuntSessionListPayloadSchema>;

export const FetchHuntSessionListResponseSchema = z.object({
  count: NonNegativeInt,
  data: z.array(HuntSessionListItemSchema),
});

export type FetchHuntSessionListResponse = z.infer<typeof FetchHuntSessionListResponseSchema>;
