import { z } from "zod";

import { NonNegativeInt, PaginationSchema, PositiveInt } from "@/lib/zod";
import { MonsterSchema } from "@/modules/bestiary";
import { CharacterIDSchema } from "@/modules/characters";
import { CharmSchema } from "@/modules/charms";
import { ItemSchema } from "@/modules/items";

import { DamageElementSchema } from "../db/damage-elements.schema";
import {
  HuntSessionDbBaseFieldsSchema,
  HuntSessionListItemSchema,
  HuntSessionSchema,
} from "../db/hunt-session.schema";
import { MonsterDamageSourceSchema } from "../db/hunt-session-relations.schema";
import { PreyBonusSchema } from "../db/prey-bonus.schema";

// ==========================================
// 🔍 READ / FETCH SCHEMAS
// ==========================================

export const FetchHuntSessionPayloadSchema = HuntSessionDbBaseFieldsSchema.pick({
  id: true,
  character_id: true,
});
export type FetchHuntSessionPayload = z.infer<typeof FetchHuntSessionPayloadSchema>;

export const FetchHuntSessionListPayloadSchema = PaginationSchema.extend({
  character_id: CharacterIDSchema,
});
export type FetchHuntSessionListPayload = z.infer<typeof FetchHuntSessionListPayloadSchema>;

export const FetchHuntSessionListResponseSchema = z.object({
  count: NonNegativeInt,
  data: z.array(HuntSessionListItemSchema),
});
export type FetchHuntSessionListResponse = z.infer<typeof FetchHuntSessionListResponseSchema>;

// ==========================================
// 📝 WRITE / MUTATION SCHEMAS (Create, Update, Delete)
// ==========================================

const HuntSessionKilledMonsterInputSchema = z.object({
  monster_id: MonsterSchema.shape.id,
  count: PositiveInt,
  prey_bonus_id: PreyBonusSchema.shape.id.nullable().optional(),
  charm_bonus_id: CharmSchema.shape.id.nullable().optional(),
});

const HuntSessionItemInputSchema = z.object({
  item_id: ItemSchema.shape.id,
  count: PositiveInt,
});

const HuntSessionDamageElementInputSchema = z.object({
  damage_element_id: DamageElementSchema.shape.id,
  percent: z.number().positive(),
});

const HuntSessionMonsterDamageSourceInputSchema = z.object({
  monster_id: MonsterDamageSourceSchema.shape.id,
  percent: z.number().positive(),
});

/**
 * Main payload for creating a new session.
 * We omit 'id' as it's generated by the database.
 */
export const CreateHuntSessionPayloadSchema = HuntSessionDbBaseFieldsSchema.omit({
  id: true,
}).extend({
  killed_monsters: HuntSessionKilledMonsterInputSchema.array(),
  looted_items: HuntSessionItemInputSchema.array(),
  supplies: HuntSessionItemInputSchema.array(),
  damage_elements: HuntSessionDamageElementInputSchema.array(),
  monster_damage_sources: HuntSessionMonsterDamageSourceInputSchema.array(),
});
export type CreateHuntSessionPayload = z.infer<typeof CreateHuntSessionPayloadSchema>;

/**
 * Used for updating existing sessions.
 * Extends create payload by requiring the session ID.
 */
export const UpdateHuntSessionPayloadSchema = CreateHuntSessionPayloadSchema.extend({
  id: HuntSessionSchema.shape.id,
});
export type UpdateHuntSessionPayload = z.infer<typeof UpdateHuntSessionPayloadSchema>;

export const DeleteHuntSessionPayloadSchema = z.object({
  id: HuntSessionSchema.shape.id,
  characterId: CharacterIDSchema,
});
