export const BLANK_SCROLL_PRICE = 25_000;
export const POWERFULL_SCROLL_MAKING_PRICE = 250_000;
export const INTRICATE_SCROLL_MAKING_PRICE = 60_000;
export const TOKENS_NEEDED_FOR_SCROLL = 6;
export const MARKET_TAX_RATE = 0.02;
